import json
import logging
import urllib.request
import urllib.error
import httpx
from typing import Dict, Any, List, Optional
from app.core.config import settings

logger = logging.getLogger("groq_ai_service")

class GroqAIService:
    """
    Groq AI Pedagogy & Student Simplifier Service.
    Leverages Groq's high-speed LPU inference (LLaMA-3.3-70B / LLaMA-3.1-8B)
    to translate dense, mathematically complex quantum analysis from NVIDIA NIM
    into intuitive, metaphor-rich, and student-friendly quantum learning content.
    """

    def __init__(self):
        self.api_key = settings.GROQ_API_KEY
        self.base_url = (settings.GROQ_BASE_URL or "https://api.groq.com/openai/v1").rstrip("/")
        self.primary_model = settings.GROQ_MODEL or "openai/gpt-oss-120b"
        self.fallback_models = [
            "openai/gpt-oss-120b",
            "openai/gpt-oss-20b",
            "qwen/qwen3.6-27b"
        ]

    def _call_chat_completions(
        self,
        system_prompt: str,
        user_prompt: str,
        max_tokens: int = 1000,
        temperature: float = 0.3
    ) -> Optional[str]:
        """
        Execute chat completion request to Groq API with fallback models.
        """
        if not self.api_key:
            return None

        url = f"{self.base_url}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
        }

        models_to_try = [self.primary_model] + [m for m in self.fallback_models if m != self.primary_model]

        connect_timeout = getattr(settings, "GROQ_CONNECT_TIMEOUT", 5.0)
        read_timeout = getattr(settings, "GROQ_READ_TIMEOUT", 15.0)
        timeout_config = httpx.Timeout(connect=connect_timeout, read=read_timeout, write=10.0, pool=5.0)

        for model in models_to_try:
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "max_tokens": max_tokens,
                "temperature": temperature
            }

            try:
                with httpx.Client(timeout=timeout_config) as client:
                    resp = client.post(url, json=payload, headers=headers)
                    if resp.status_code == 200:
                        resp_data = resp.json()
                        choices = resp_data.get("choices", [])
                        if choices and len(choices) > 0:
                            msg = choices[0].get("message", {})
                            content = (msg.get("content") or msg.get("reasoning") or "").strip()
                            if content:
                                return content
                    elif resp.status_code in (401, 403):
                        logger.warning(f"Groq authentication failed ({resp.status_code}); skipping further model retries.")
                        break
                    else:
                        logger.warning(f"Groq API call returned HTTP {resp.status_code} on model '{model}'")
            except Exception as e:
                logger.warning(f"Groq API call failed on model '{model}': {e}")

        return None

    def optimize_response(
        self,
        nvidia_reasoning: str,
        question: str,
        context: Dict[str, Any],
        level: str = "beginner"
    ) -> Dict[str, Any]:
        """
        Alias/adapter matching AIOrchestrator interface for Groq refinement.
        """
        res = self.simplify_explanation(nvidia_reasoning, question, context, level)
        return {
            "optimized_text": res.get("simplified_text", ""),
            "simplified_by": res.get("simplified_by", "groq"),
            "model": res.get("model", self.primary_model)
        }

    def simplify_explanation(
        self,
        nvidia_analysis: str,
        question: str,
        circuit_context: Dict[str, Any],
        level: str = "beginner"
    ) -> Dict[str, Any]:
        """
        Takes the deep, dense quantum analysis generated by NVIDIA NIM and transforms
        it into an intuitive, student-friendly explanation using the Groq API.
        """
        circ = circuit_context.get("circuit", {})
        qubits = circ.get("qubits", 2)
        gates = circ.get("gates", [])
        gate_summary = ", ".join([g.get("gate", "").upper() for g in gates]) if gates else "empty circuit"

        system_prompt = (
            "You are the Qualution Quantum Student Pedagogue & Mentor, powered by Groq LPU inference. "
            "Your vital mission is to take the complex, dense, and math-heavy quantum analysis produced by "
            "the NVIDIA quantum physics engine and rewrite it so that a student can easily understand, "
            "visualize, and enjoy learning it.\n\n"
            f"Target Student Level: {level.upper()}.\n\n"
            "Key Pedagogical Principles:\n"
            "1. INTUITION & METAPHORS FIRST: Explain what happens using relatable physical metaphors:\n"
            "   - Superposition = a spinning coin in mid-air (simultaneously heads and tails until caught/measured).\n"
            "   - Entanglement = a magical pair of dice or linked shoes; look at one, and you instantly know the other, even across galaxies.\n"
            "   - Phase rotations (Z, S, T) = turning the face of a clock or compass needle around the equator.\n"
            "   - Hadamard (H) = setting the coin spinning.\n"
            "   - Pauli-X = a clean quantum flip (flipping a switch or inverting a coin).\n"
            "   - CNOT (CX) = an interactive decision gate: 'flip the target only if the control is active'.\n"
            "2. TRANSLATE DENSE FORMULAS INTO PLAIN ENGLISH:\n"
            "   - When Dirac kets like |0>, |1>, |+>, or matrix products are mentioned in the NVIDIA analysis, explain what they mean conceptually rather than leaving the student baffled.\n"
            "3. ACTIONABLE CIRCUIT INSIGHTS:\n"
            "   - Tell the student directly what to observe in the Qualution Studio (e.g. 'Look at the Statevector amplitude bar', 'Notice the 50/50 measurement probabilities').\n"
            "4. CLEAR STUDENT-FRIENDLY STRUCTURE:\n"
            "   - Start with a clear 1-2 sentence direct answer in welcoming language.\n"
            "   - Provide '🧠 The Intuition' explaining the concept with the metaphor.\n"
            "   - Provide '🔬 What Happens in Your Circuit' breaking down the gate sequence.\n"
            "   - End with '💡 Key Takeaway for Students' with 1-2 bite-sized bullet points.\n"
            "5. TONE: Warm, encouraging, scientifically accurate, and completely devoid of dry academic jargon."
        )

        user_prompt = (
            f"Student Question: {question}\n"
            f"Circuit Summary: {qubits} qubit(s), gates: [{gate_summary}]\n\n"
            f"--- NVIDIA NIM Quantum Analysis (To be simplified for students) ---\n"
            f"{nvidia_analysis}\n"
            f"------------------------------------------------------------------\n\n"
            f"Please translate this technical analysis into an engaging, crystal-clear, student-friendly explanation."
        )

        groq_output = self._call_chat_completions(system_prompt, user_prompt, max_tokens=900, temperature=0.35)

        if groq_output:
            return {
                "simplified_text": groq_output,
                "simplified_by": "groq",
                "model": self.primary_model
            }

        # Resilient heuristic student simplifier if external Groq API is offline/unconfigured
        return {
            "simplified_text": self.heuristic_student_simplifier(nvidia_analysis, question, level),
            "simplified_by": "groq-heuristic-fallback",
            "model": "heuristic-pedagogue"
        }

    def heuristic_student_simplifier(
        self,
        nvidia_analysis: str,
        question: str,
        level: str = "beginner"
    ) -> str:
        """
        Rule-based pedagogical transformer that unpacks dense academic jargon into
        approachable student sections with intuitive metaphors.
        """
        analysis_lower = (nvidia_analysis + " " + question).lower()

        # Identify core quantum concept
        metaphor = ""
        if "superposition" in analysis_lower or "hadamard" in analysis_lower or "50/50" in analysis_lower:
            metaphor = (
                "🪙 **Think of it like a spinning coin**: When you flip a coin into the air, while it is spinning, "
                "it isn't strictly Heads or strictly Tails—it is in a dynamic blend of both possibilities at once. "
                "Only when you catch it (measure it) does it snap into a definite state!"
            )
        elif "entangle" in analysis_lower or "bell" in analysis_lower or "cx" in analysis_lower or "cnot" in analysis_lower:
            metaphor = (
                "🎲 **Think of it like paired dice**: Imagine two magical dice rolled in separate rooms. "
                "Whenever die #1 lands on 6, die #2 is guaranteed to land on 6, perfectly synchronized! "
                "That's quantum entanglement: the qubits share a single intertwined destiny."
            )
        elif "phase" in analysis_lower or "bloch" in analysis_lower or "rotation" in analysis_lower:
            metaphor = (
                "🧭 **Think of it like a compass needle**: Changing a qubit's quantum phase is like turning a compass needle "
                "around the equator of a sphere. The probability of measuring 0 or 1 might remain the same, but the needle points in a different direction, allowing wave interference!"
            )
        elif "optimal" in analysis_lower or "optimize" in analysis_lower or "redundant" in analysis_lower:
            metaphor = (
                "⚡ **Think of it like clearing clutter**: Redundant gates are like taking a step forward and immediately taking a step backward. "
                "Removing them keeps the quantum system crisp and prevents environmental noise from ruining the computation."
            )
        else:
            metaphor = (
                "🌊 **Think of it like ocean waves**: In quantum mechanics, probabilities behave like overlapping ripples on water. "
                "Waves can reinforce each other (constructive interference) or cancel each other out (destructive interference)."
            )

        # Clean dense notation from raw text for the student breakdown
        clean_summary = nvidia_analysis.replace("Dirac", "quantum state").replace("Hamiltonian", "energy operator")
        paragraphs = [p.strip() for p in clean_summary.split("\n\n") if p.strip()]
        first_para = paragraphs[0] if paragraphs else "Quantum gates manipulate the quantum state of qubits through unitary transformations."

        # Strip markdown headers from first paragraph if any
        if first_para.startswith("#"):
            lines = first_para.split("\n")
            first_para = "\n".join([l for l in lines if not l.startswith("#")]).strip()

        return (
            f"### 🎓 Student-Friendly Quantum Explanation\n\n"
            f"{first_para}\n\n"
            f"#### 🧠 The Intuitive Metaphor\n"
            f"{metaphor}\n\n"
            f"#### 🔬 What This Means on Your Circuit\n"
            f"- **Step-by-step**: Each gate on your timeline transforms the qubit state smoothly before measurement.\n"
            f"- **Look at the Studio**: Check the **State** tab to see probability amplitudes, or open the **3D Bloch Sphere** to watch the state vector rotate!\n\n"
            f"> 💡 **Key Student Takeaway**: Quantum qubits are not just classical 0s and 1s; they harness superposition and phase interference so we can explore all possibilities simultaneously."
        )

    def direct_tutor(
        self,
        question: str,
        circuit_context: Dict[str, Any],
        mode: str = "explain",
        level: str = "beginner"
    ) -> Optional[str]:
        """
        Direct high-speed tutoring via Groq if NVIDIA NIM is unavailable.
        """
        circ = circuit_context.get("circuit", {})
        qubits = circ.get("qubits", 2)
        gates = circ.get("gates", [])
        gate_summary = ", ".join([g.get("gate", "").upper() for g in gates]) if gates else "empty"

        system_prompt = (
            "You are the Qualution Quantum AI Tutor powered by Groq LPU inference. "
            "You are an inspiring, friendly, and patient quantum computing professor for students. "
            f"Active Mode: {mode.upper()}. Learner Level: {level.upper()}.\n\n"
            "Principles:\n"
            "1. Explain complex quantum concepts with vivid everyday metaphors first.\n"
            "2. Provide step-by-step guidance on what happens in the circuit.\n"
            "3. Conclude with a clear 'Key Takeaway for Students'."
        )

        user_prompt = (
            f"Circuit: {qubits} qubits, gates: [{gate_summary}]\n"
            f"Student Question: {question}"
        )

        return self._call_chat_completions(system_prompt, user_prompt, max_tokens=900, temperature=0.3)

groq_ai_service = GroqAIService()
